Add modified date for AssetPathEntity
CaiJingLong/flutter_photo_manager pull request #466
Opened 2021-03-30 06:35 UTC by CaiJingLong

2021-03-30 06:36 UTC, CaiJingLong commented
@AlexV525  
Your Feature, you can verify it.

2021-03-30 09:19 UTC, AlexV525 requested changes
Tested. Overall the feature is good to go on Android, but one place still need to be fix.

2021-03-30 09:19 UTC, AlexV525 commented on lib/src/filter/filter_options.dart
> +    result['containsPathModified'] = containsPathModified;
Lack of `this.containsPathModified = other.containsPathModified` in `merge` method.

2021-03-31 02:55 UTC, CaiJingLong commented
Regarding the parameter name, do you have any comments?  We can modify it before merging.
Once released, it will trigger a breaking change.

2021-03-31 03:29 UTC, AlexV525 commented on lib/src/filter/filter_options.dart
> +import 'package:photo_manager/photo_manager.dart';
Could we import the minimal reference?

2021-03-31 03:31 UTC, AlexV525 commented
> @AlexV525 Regarding the parameter name, do you have any comments? We can modify it before merging.

Maybe `lastModified`, `updateAt` or `modifiedAt` ? Can't tell which one is better cause IMO they are all the same.

2021-03-31 03:40 UTC, CaiJingLong commented
Are there any suggestions for the field in filterOption?

2021-03-31 06:24 UTC, AlexV525 commented
`FilterOption` looks good. `FilterOptionGroup` seems can be refactored with the constructor, it's `copyWith` method also behaves slightly different from common copy with methods. For example:

```yaml
class FilterOptionGroup {
  FilterOptionGroup({
    FilterOption? imageOption,
    FilterOption? audioOption,
    FilterOption? videoOption,
    this.containsEmptyAlbum = false,
    this.containsPathModified = false,
  });
}
```

Also deprecated methods can be removed.

2021-04-02 05:38 UTC, CaiJingLong commented
> `FilterOption` looks good. `FilterOptionGroup` seems can be refactored with the constructor, it's `copyWith` method also behaves slightly different from common copy with methods. For example:
> 
> ```dart
> class FilterOptionGroup {
>   FilterOptionGroup({
>     FilterOption? imageOption,
>     FilterOption? audioOption,
>     FilterOption? videoOption,
>     this.containsEmptyAlbum = false,
>     this.containsPathModified = false,
>   });
> }
> ```
> 
> Also deprecated methods can be removed.

The PR only add new feature.
I will open new pull request to update ctor.

2021-04-02 05:38 UTC, merged